# ============================================================================
# DOCKER COMPOSE - DEVELOPMENT MODE (Hot-Reload)
# ============================================================================
#
# Este docker-compose extiende el principal y agrega configuración para desarrollo
# con hot-reload usando Air (Go) y volúmenes montados
#
# Uso:
#   docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
#
# Features:
#   - Hot-reload con Air para Inventory Service (Go)
#   - Volúmenes montados para edición en vivo
#   - Puerto de debugging expuesto (Delve para Go)
#
# ============================================================================

version: "3.8"

services:
  # ============================================================================
  # Inventory Service (Go) - Desarrollo con Air
  # ============================================================================
  inventory-service:
    build:
      context: ./services/inventory-service
      dockerfile: Dockerfile.dev # Usa Dockerfile.dev para hot-reload
      target: development
    volumes:
      # Montar código fuente para hot-reload
      - ./services/inventory-service:/app:rw
      # Excluir bin y tmp del host (usar los del contenedor)
      - /app/bin
      - /app/tmp
    environment:
      - GIN_MODE=debug # Modo debug de Gin (más verbose)
      - AIR_ENABLED=true # Indicador de que Air está activo
      - LOG_LEVEL=debug # Logs detallados en desarrollo
    ports:
      - "2345:2345" # Puerto para Delve debugger (Go)


  # ============================================================================
  # Orders Service (NestJS) - Ya tiene hot-reload en docker-compose.yml
  # ============================================================================
  # El Dockerfile principal ya usa target: development con volúmenes montados
  # No necesita override adicional para hot-reload
